export const IconsMap = {
    subway_d:  "http://localhost:4200/assets/img/subway_d.svg",
    subway: "http://localhost:4200/assets/img/subway.svg",
    bus_d: "http://localhost:4200/assets/img/bus_d.svg",
    bus: "http://localhost:4200/assets/img/bus.svg",
    taxi: "http://localhost:4200/assets/img/taxi.svg",
    house: "http://localhost:4200/assets/img/house.svg",
    account: "http://localhost:4200/assets/img/account.svg",
    store: "http://localhost:4200/assets/img/store.svg",
    deliver: "http://localhost:4200/assets/img/deliver.svg",
    deliver_d: "http://localhost:4200/assets/img/deliver_d.svg",
    crime: "http://localhost:4200/assets/img/gun.svg",
    crime_d: "http://localhost:4200/assets/img/crime_d.svg",
    vehicle: "http://localhost:4200/assets/img/vehicle.svg",
    vehicle_d: "http://localhost:4200/assets/img/vehicle_d.svg",
    kidnapping: "http://localhost:4200/assets/img/kidnapping.svg",
    rape: "http://localhost:4200/assets/img/rape.svg",
    gun: "http://localhost:4200/assets/img/gun.svg",
}

