export const IconsMap: Array<string> = [
    "http://localhost:4200/assets/img/subway.svg",
    "http://localhost:4200/assets/img/subway_d.svg",
    "http://localhost:4200/assets/img/bus_d.svg",
    "http://localhost:4200/assets/img/bus.svg",
    "http://localhost:4200/assets/img/taxi.svg",
    "http://localhost:4200/assets/img/house.svg",
    "http://localhost:4200/assets/img/account.svg",
    "http://localhost:4200/assets/img/store.svg",
    "http://localhost:4200/assets/img/deliver.svg",
    "http://localhost:4200/assets/img/deliver_d.svg",
    "http://localhost:4200/assets/img/crime.svg",
    "http://localhost:4200/assets/img/crime_d.svg",
    "http://localhost:4200/assets/img/vehicle.svg",
    "http://localhost:4200/assets/img/vehicle_d.svg",
    "http://localhost:4200/assets/img/kidnapping.svg",
    "http://localhost:4200/assets/img/rape.svg",
    "http://localhost:4200/assets/img/gun.svg",
]

